sudo: false
language: java

before_install:
- unset -v _JAVA_OPTIONS
- wget https://github.com/sormuras/bach/raw/support-older-jdks/install-jdk.sh

matrix:
  include:
  - os: linux
    env: Java='5'
  - os: linux
    env: Java='6'
  - os: linux
    env: Java='7'
  - os: linux
    env: Java='8'
  - os: linux
    env: Java='9'
  - os: linux
    env: Java='10'
  - os: linux
    env: Java='11'
  - os: linux-ppc64le
    env: Java='8'  URL="https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u222-b10/OpenJDK8U-jdk_ppc64le_linux_hotspot_8u222b10.tar.gz"
  - os: linux-ppc64le
    env: Java='9'  URL="https://github.com/AdoptOpenJDK/openjdk9-binaries/releases/download/jdk-9.0.4%2B11/OpenJDK9U-jdk_ppc64le_linux_hotspot_9.0.4_11.tar.gz"
  - os: linux-ppc64le
    env: Java='10' URL="https://github.com/AdoptOpenJDK/openjdk10-binaries/releases/download/jdk-10.0.2%2B13.1/OpenJDK10U-jdk_ppc64le_linux_hotspot_10.0.2_13.tar.gz"
  - os: linux-ppc64le
    env: Java='11' URL="https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.4%2B11/OpenJDK11U-jdk_ppc64le_linux_hotspot_11.0.4_11.tar.gz"
  - os: linux-ppc64le
    env: Java='12' URL="https://github.com/AdoptOpenJDK/openjdk12-binaries/releases/download/jdk-12.0.2%2B10/OpenJDK12U-jdk_ppc64le_linux_hotspot_12.0.2_10.tar.gz"

install:
- if [ "$HOSTTYPE" == "powerpc64le" ]; then source ./install-jdk.sh --verbose --url ${URL} --feature ${Java}; fi
- if [ "$HOSTTYPE" == "x86_64" ]; then source ./install-jdk.sh --verbose --resurrect --feature ${Java}; fi

script:
- echo PATH = ${PATH}
- echo JAVA_HOME = ${JAVA_HOME}
- java -version
