dist: xenial
language: java
jdk: openjdk13

install:
- java --version

script:
- jshell --execution local ./build.jsh

after_success:
- BACH=${TRAVIS_BUILD_DIR}/src/bach/Bach.java

- cd "${TRAVIS_BUILD_DIR}/demo"
- java -Debug ${BACH}
